### ISSUE TITLE
If notifications fail reservation endpoint returns 500

### ISSUE THREAD

**Issue by igordavydsson** [City-of-Helsinki/berth-reservations#34]
Even though only notification failed and reservation was successfully created, our reservations endpoint returns 500. This makes front freeze and prevents it from going to success page.

**Comment by vikoivun** [comment]
Found this. You're calling capturexception in the signal handler, which does not accept an exception but instead exc_info structure. Try capturemessage as the quickest fix.

**Comment by igordavydsson** [comment]
Fixd in #52
